Update download-cache.yml

diff --git a/.github/workflows/download-cache.yml b/.github/workflows/download-cache.yml
--- a/.github/workflows/download-cache.yml
+++ b/.github/workflows/download-cache.yml
@@ -1,4 +1,4 @@
-name: Archive download sources weekly
+name: "Mirror sources to dl.static-php.dev"
 
 on:
   workflow_dispatch:
@@ -7,58 +7,92 @@ on:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  PHP_VERSION: 8.4
 
 jobs:
-  download:
-    name: "Archive downloads to zip"
-    runs-on: macos-14
-    steps:
+  # define
+  define-matrix:
+    name: "Generate source matrix"
+    runs-on: ubuntu-latest
+    outputs:
+      sources: ${{ steps.step1.outputs.sources }}
+    steps: 
       - name: "Checkout"
         uses: "actions/checkout@v4"
         with:
           repository: crazywhalecc/static-php-cli
 
-      - name: "Download SPC bin artifact for self-hosted runners"
-        uses: dawidd6/action-download-artifact@v2
+      - name: "Create Matrix Variable"
+        id: step1
+        run: |
+          VALUE=$(cat config/source.json | jq -M -c keys)
+          echo 'sources='"$VALUE" >> "$GITHUB_OUTPUT"
+
+  # parse
+  download-source:
+    name: "Download ${{ matrix.source }}"
+    runs-on: ubuntu-latest
+    needs: define-matrix
+    timeout-minutes: 60
+    strategy:
+      matrix:
+        source: ${{ fromJSON(needs.define-matrix.outputs.sources) }}
+      fail-fast: false
+    steps:
+      - name: "Checkout"
+        uses: "actions/checkout@v4"
         with:
-          repo: crazywhalecc/static-php-cli
-          branch: main
-          workflow: release-build.yml
-          name: "spc-macos-aarch64"
-
-      - name: "Validate SPC bin"
+          repository: crazywhalecc/static-php-cli
+      - name: "Setup static-php environment"
         run: |
-          chmod +x spc
-          ./spc --version
-
-
-      # If there's no dependencies cache, fetch sources, with or without debug
-      - name: "Download all sources"
+          bin/setup-runtime
+          bin/php bin/composer install --no-dev --no-ansi -q --no-interaction
+      - name: "Download source ${{ matrix.source }}"
+        run: bin/php bin/spc download ${{ matrix.source }} --debug --ignore-cache-sources
+      - name: "Parse lock file and re-package with file"
         run: |
-          ./spc download --all --debug --retry=5 --shallow-clone
-
-      # Upload downloaded files
-      - name: "Upload action artifacts"
-        uses: actions/upload-artifact@v4
-        with:
-          name: download-files-${{ matrix.php-version }}
-          path: downloads/
-
-      - name: "Archive downloads as zip"
-        run: |
-          cd downloads/
-          zip -r download-files-${{ env.PHP_VERSION }}.zip .
-          mkdir ../downloads-archive/
-          mv download-files-${{ env.PHP_VERSION }}.zip ../downloads-archive/
-          cd ..
-
-      - name: "Deploy to self-hosted OSS"
+          rename_file() {
+              local src_file="$1"
+              local target="$2"
+              
+              if [[ ! -f "$src_file" ]]; then
+                  echo "Error: '$src_file' is not a valid file" >&2
+                  return 1
+              fi
+              
+              if [[ "$src_file" =~ \.tar\.(gz|xz)$ ]]; then
+                  local ext=".tar.${BASH_REMATCH[1]}"
+                  local base_name="${src_file%$ext}"
+                  if [[ -z "$base_name" ]]; then
+                      echo "Error: Invalid filename '$src_file'" >&2
+                      return 1
+                  fi
+                  
+              elif [[ "$src_file" =~ \.[^./]+$ ]]; then
+                  local ext=".${src_file##*.}"
+                  local base_name="${src_file%.$ext}"
+              else
+                  echo "Skip: '$src_file' has no extension" >&2
+                  return 0
+              fi
+              
+              local new_name="${target}${ext}"
+              cp -- "$src_file" "$new_name"
+              echo "Renamed: $src_file -> $new_name"
+          }
+          SOURCE_TYPE=$(cat downloads/.lock.json | jq -M -c -r '."${{ matrix.source }}".source_type'
+          if [ "$SOURCE_TYPE" = "archive" ]; then
+            rename_file $(cat downloads/.lock.json | jq -M -c -r '."${{ matrix.source }}".filename') ${{ matrix.source }}-spc-mirror
+          else
+            cd downloads
+            tar -cJvf ${{ matrix.source }}-spc-mirror.txz $(cat downloads/.lock.json | jq -M -c -r '."${{ matrix.source }}".dirname')
+            cd ..
+          fi
+      - name: "Deploy to OSS"
         uses: shallwefootball/s3-upload-action@master
         with:
           aws_key_id: ${{ secrets.AWS_KEY_ID }}
           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws_bucket: ${{ secrets.AWS_BUCKET }}
-          source_dir: downloads-archive/
-          destination_dir: static-php-cli/deps/downloads-archive/
+          source_dir: downloads/${{ matrix.source }}-spc-mirror.txz
+          destination_dir: static-php-cli/deps/spc-download-mirror/
           endpoint: ${{ secrets.AWS_ENDPOINT }}
